global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${ALERT_EMAIL_FROM}'
  smtp_auth_username: '${ALERT_EMAIL_USER}'
  smtp_auth_password: '${ALERT_EMAIL_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email'
  routes:
    - match:
        severity: 'critical'
      receiver: 'email-critical'
    - match:
        severity: 'warning'
      receiver: 'email-warning'

receivers:
- name: 'email'
  email_configs:
  - to: '${ALERT_EMAIL_TO}'
    send_resolved: true
    headers:
      subject: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
    html: |
      <h2>Alert Details</h2>
      <table>
        <tr><td><strong>Status</strong></td><td>{{ .Status | toUpper }}</td></tr>
        <tr><td><strong>Alert Name</strong></td><td>{{ .CommonLabels.alertname }}</td></tr>
        <tr><td><strong>Severity</strong></td><td>{{ .CommonLabels.severity }}</td></tr>
        <tr><td><strong>Instance</strong></td><td>{{ .CommonLabels.instance }}</td></tr>
        <tr><td><strong>Summary</strong></td><td>{{ .CommonAnnotations.summary }}</td></tr>
        <tr><td><strong>Description</strong></td><td>{{ .CommonAnnotations.description }}</td></tr>
      </table>
      <h3>Alerts</h3>
      <table>
        <tr>
          <th>Status</th>
          <th>Labels</th>
          <th>Starts At</th>
        </tr>
        {{ range .Alerts }}
        <tr>
          <td>{{ .Status }}</td>
          <td>
            {{ range .Labels.SortedPairs }}
              {{ .Name }}: {{ .Value }}<br>
            {{ end }}
          </td>
          <td>{{ .StartsAt }}</td>
        </tr>
        {{ end }}
      </table>

- name: 'email-critical'
  email_configs:
  - to: '${ALERT_EMAIL_CRITICAL}'
    send_resolved: true
    headers:
      subject: '[CRITICAL] {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}'

- name: 'email-warning'
  email_configs:
  - to: '${ALERT_EMAIL_TO}'
    send_resolved: true
    headers:
      subject: '[WARNING] {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}'
