global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Rule files
rule_files:
  - 'alert.rules'

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape application metrics
  - job_name: 'scrambled-eggs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
    # Add basic auth if needed
    # basic_auth:
    #   username: '${METRICS_USER}'
    #   password: '${METRICS_PASSWORD}'

  # Scrape Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  # Scrape PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Scrape cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  # Scrape Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
    metrics_path: '/metrics'

# Remote write configuration (optional, for long-term storage)
# remote_write:
#   - url: 'http://thanos:10908/api/v1/receive'
#     queue_config:
#       max_samples_per_send: 10000
#       max_shards: 200
#       capacity: 2500
